### ISSUE TITLE
Can't access Vault secrets

### ISSUE THREAD

**Issue by voodooGQ** [SpectralOps/teller#18]
I'll preface this by saying I'm pretty new to Vault in general, and odds are I'm just doing something incorrectly. For some reason Teller is unable to read from my Vault cluster. I've done several different combinations of secret locations to try and get it to read, for example:

- `secret/data/{{stage}}/test/teller`
- `secret/data/{{stage}}/test`
- `secrets/{{stage}}/test/teller`
- `secrets/{{stage}}/test`
- `{{stage}}/test/teller`
- `{{stage}}/test`

Regardless of what I use I get back the error that `data not found at <insert_vault_string>`. However, I am able to read it just fine by running the `vault kv get developement/test/teller` directive. Any insight into what I may be doing wrong here?

Teller Config:
```yaml
project: teller-test
confirm: Are you sure you want to run on {{stage}}?
opts:
  region: env:AWS_REGION
  stage: development
providers:
  hashicorp_vault:
    env_sync:
      path: 'secret/data/{{stage}}/test/teller'
    env:
      TELLER_TEST_SECRET:
        path: '{{stage}}/test'
        field: teller
```

Screenshot of Vault store:

![image](https://user-images.githubusercontent.com/1512028/119840331-85a84200-beca-11eb-9fec-c8bc9cf06197.png)

Screenshot of terminal call:

![image](https://user-images.githubusercontent.com/1512028/119840396-98227b80-beca-11eb-96f7-0ec4271d2c3f.png)
