### ISSUE TITLE
Support hashicorp vault database secrets engine

### ISSUE THREAD

**Issue by derektamsen** [SpectralOps/teller#4]
I think `teller` may be able to help a use case that I have in fetching hashicorp vault dynamic database secrets. The [dynamic database secrets engine](https://www.vaultproject.io/docs/secrets/databases) creates and returns a username and password for databases. This is useful for security reasons but can be cumbersome when using database clients such as `psql` or `mysql`.

I think teller might be helpful by fetching the dynamic username and password from vault, setting the correct environment variables, and runing the database client. However, the data structure returned by vault is slightly different than the kv data structure.

The [vault kv data structure containing secrets](https://www.vaultproject.io/api/secret/kv/kv-v2#sample-response-1) returns a double `data.data{}` object. Whereas the [vault database secrets engine](https://www.vaultproject.io/api/secret/databases#sample-response-4) returns `data{}`.

If teller supported the database endpoint the following `.teller.yml` could be used to set the [correct environment variables and connect to postgres](https://www.postgresql.org/docs/13/libpq-envars.html):
```yaml
project: postgres_client
providers:
  hashicorp_vault:
    env:
      PGUSER:
        path: database/creds/my-role
        field: username
      PGPASSWORD:
        path: database/creds/my-role
        field: password
```
Then, one could connect to the database using `psql`:
```shell
teller run psql -h db.example.com -d postgres
```

I think support could be added to teller by adjusting the double `data.data{}` assumptions in [hashicorp_vault.go#L60](https://github.com/SpectralOps/teller/blob/master/pkg/providers/hashicorp_vault.go#L60) and [hashicorp_vault.go#L84](https://github.com/SpectralOps/teller/blob/master/pkg/providers/hashicorp_vault.go#L84).

Any thoughts on this? I can open a PR if their is interest.

**Comment by artis3n** [comment]
Dynamic credentials from Vault is what first drew my attention to this repo. Big 👍 on supporting the dynamic database secrets engine responses.

**Comment by jondot** [comment]
This sounds perfect, @derektamsen go ahead and I will happily accept. Also if there's anything you need help with - feel free to let me know 👍

**Comment by derektamsen** [comment]
Great! Thanks! I will see what I can do and let you know if I am stuck on something.

**Comment by derektamsen** [comment]
@jondot I opened #5 to add support for `data{}` and `data.data{}` in the vault provider. It was a bit more complex then I initially thought. The issue was that vault will return a new dynamic user + password for every read request to the dynamic database secrets backend path. As a result my initial example in the issue would result in a mismatched username + password (username1 + password2). Instead of making the `path` read atomic and setting all environment variables from a single read for `env` I added the ability to remap keys returned from `env_sync`. This should allow any key returned from the provider to be remapped to a different local environment variable. This means following is now possible:

```yaml
project: postgres_client
providers:
  hashicorp_vault:
    env_sync:
      path: database/roles/my-role
      remap:
        username: PGUSER
        password: PGPASSWORD
```

Now `teller env` will return the following (also works with all of the other teller methods):

```shell
PGUSER=username_generated_by_vault
PGPASSWORD=password_generated_by_vault
```
