### ISSUE TITLE
Cloudflare worker secrets Write-only Providers support

### ISSUE THREAD

**Issue by jkirkpatrick24** [SpectralOps/teller#42]
Hello 👋 !

I was having a look though the teller roadmap and see that there are plans for adding "write only" provider support. I think this is an excellent Idea and would be something would be really useful. In particular for our team, adding support for [cloudflare workers secrets](https://github.com/cloudflare/cloudflare-go/blob/master/workers_secrets.go) would be extremely useful for our workflows. I would be happy to contribute a PR for this.

Has there been any work put into designing/implementing this feature yet?

Cheers

**Comment by lreuven** [comment]
Hi @jkirkpatrick24,
Great idea! we will be happy to accept your contribution, no work was done for this ER till now.
Let us know if you need any assistance,

Take care

**Comment by jkirkpatrick24** [comment]
Hi @lreuven, I've done a bit of thinking about the write-only provider support feature that would be necessary for this and would love to get your (and the other maintainers) take on the best approach for how this should work. I've outlined some of my thinking below. Please let me know if this is roughly in line with what the teller team was envisaging of if I've missed the mark here. 
 
Cheers!
# WriteProviders

One of the things I like most about teller is how declarative it is. You defined you environment in a configuration file so its clear what its being injected into your application and where from. It would be great to be able to maintain this declarative nature for the write-only providers. I think it would be really useful to be able to define write only providers alongside core providers in order to clearly show how they are coupled together.

e.g

```yaml
project: hello-world
opts:
  update_write_only: env:WRITE_CF_WORKER_SECRET
providers:
  aws_ssm:
    env:
      SECRET_KEY:
        path: /{{project}}/{{environment}}/secret_key
        decrypt: true
  heroku:
    env:
      DATABASE_URL:
        path: hello-world-{{environment}}

# declare write only providers (V1)
write_providers:
  cloudflare_workers_secrets:
    write: true # could be set to false to turn of write operations based on env.
    # Name of the provider to take ENV entries from
    from:
      - aws_ssm
      - heroku
    env:
      # write the following entries as-is to the write only provider
      - DATABASE_URL
      - SECRET_KEY

# V2 could add support for syncing providers, so grab all secrets from listed
# providers and write all entries to the write only provider.
```
## Architecture Ideas

- Does it make sense to use the existing provider interface for this? My initial feeling would be that it should be its own interface, without the Get operations. This leaves rooms for extending the features from providers if write only and core provider functionality diverges, without requiring additional changes to existing providers to satisfy an interface that isn't necessarily going to be used. Although, I'm not sure how likely that is.

The Write provider would look like:
```go
type WriteProvider interface {
	Name() string
	Put(p KeyPath, val string) error
	PutMapping(p KeyPath, m map[string]string) error
}
```

### Some other general thoughts/questions
- When should the "write" step occur?
  - It should probably have its own command, something like `teller write`?

- Is there any other time it would make sense? Maybe a flag would be reasonable.
  I could envision a use case where I execute a teller file when running/building an application, but I want to update a write only environment at the same time (e.g cloudflare workers secrets). A command would be something like

  `teller run --write-providers=true -- npm run deploy`

  In this use case, the env would be loaded from all core providers first using [Collect](https://github.com/SpectralOps/teller/blob/master/pkg/teller.go#L421), then before the command that has been passed to teller (npm run deploy), we update the writeProviders with the envs that have already been fetched. Once that happens, we execute the command and provider the loaded env.
