### ISSUE TITLE
STDIN Shell Provider

### ISSUE THREAD

**Issue by brandonwestcott** [SpectralOps/teller#44]
Just came across this tool, super great. Been in devops for a few years and this definitely solves a need. Love the support for multiple providers within a single invocation.

I'm personally interested in gopass (#11) for some local only api keys. While I fully appreciate first class integration with providers, I'm wondering if #3 #10 #11 (and other future requests) could all be achieved if there was a generic `shell` provider. Using that provider would just invoke that shell script with a known STDIN api, ex `[command] [path] [options]`.

**Comment by lreuven** [comment]
@brandonwestcott Hi 👋
Apologizes for the late replay, 
Can you share a bit more about this ER? not sure how teller will fits into this use case.

**Comment by brandonwestcott** [comment]
@jondot yes exactly. Quick escape hatch for devs to use other tools that aren't yet supported providers.

**Comment by jondot** [comment]
First design:

```
  cli:
    env_sync:
      path: '' # fmt k=v, ignore empty or no '='. also first '=' counts. take a splitter as optional config
      meta: env
    env:
      FOO_BAR:
        path: foo/bar/baz
        meta: echo ${{path|key}}  # fmt v, also take first line
```

1. Interchange format was hard. Eventually, go with the environment format (`k=v`) (and not impose structuring JSONs etc). Specific key just expects value on STDOUT
2. Concluded that there must be an introduction of a new 'meta' key. For CLI provider this will be the command. a meta key is also a gotemplate, and we will provide it with the entry itself for substitution.
3. Cmd execution is simple exec

@kaplanelad WDYT? got some feedback? specifically on the interchange format or new `meta` key
