### ISSUE TITLE
Error: provider 'gopass' does not exist%

### ISSUE THREAD

**Issue by patrickc-sb** [SpectralOps/teller#87]
## Expected Behavior
Accessing secrets stored in gopass password-store

## Current Behavior
.teller.yaml provider configuration for gopass always throws:
`Error: provider 'gopass' does not exist%`

Provider config for gopass:
```
#
# Providers
#
providers:
  gopass:
    env_sync:
      path: /path/to/gopass/password-store
``` 

Gopass is also installed and working on my MacBook.

I'm not sure what I'm missing here. I'd be thankful for any pointers.

Thanks in advance!

## Steps to Reproduce

1. `teller new`
2. Add gopass configuration to .teller.yaml
3. `teller show`
4. Above mentioned error appears

## Context
I'd like to use gopass as a secret backend.

## Specifications
  - Version: `$ teller version` => 1.4.0
  - Platform: masOS
